
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      url: https://192.168.50.193:9443/mutate-batch-tutorial-chanshik-dev-v1-cronjob
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhRENDQTFDZ0F3SUJBZ0lVRXMwbEFqWWZMUm45NnhpOVhyaHNadmlZcmNJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hqRWNNQm9HQTFVRUF3d1RkMlZpYUc5dmF5NWpjbTl1YW05aUxuTjJZekFlRncweU1UQTFNVEF3TlRVNQpNRFphRncweU1qQTFNVEF3TlRVNU1EWmFNQjR4SERBYUJnTlZCQU1NRTNkbFltaHZiMnN1WTNKdmJtcHZZaTV6CmRtTXdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFERE43ckFydXlQNmNuUVFYeW0KRk13dnRoYW1mbDIvSG5Tc2FDUmNhYTVOMWRETU9FcWRKc25MeVN4L1J0MWxPOVQxWmNjSkRZanRla1hmYWE1MgpvMDYyZE1HZGlJVHN5LzNpUmRDU0JVcXA1WnVVR3FGeE1lbkk1bDRSTjh0OFMwSnFsRlJUZlNSUHFyYUR5VWdaCnZoUHBYckJ1RXlpS1NEK1hQeDdTdHJheWNmM1NrMG9WVGhPZVlEWHYvV2JzdVpDOGhWMHR1OVp3OGhIamlsWGEKVHZwNVR6NDl6THlPQ09EM2I4OHBIa1FzbG80TkVZZkVGYnZFS2VWQkYyZzRJaHlLSmVoaTlySWR0MlpHcnlzQwpua3k0UitEVXVaZGk0N0JYN1pVdUE2azE2QnZUTjNVMmdlSFFJbTVDaFJtVjFxdGFPNVZ0NVNUTjRIbVF1alNrCkk2VUpnUktWQ2JmblJ2N3hha1QreHpQK3Bjb1h4ME94dWdPQ042LzVCY2k5UzBDVmVNM25EMVNHcG5rdHl0QnkKR1ZpZzM4RVRVUTNkdzJVaFd5QkFJdG9JT1p5VGRCdnNVTm9LT29sNjcwemJSMnRKRGJpdXZNZ20rTVhuV1YvbgpwQ1N1UWZFTDYxU1JLditvdkZiZklqUUt3ZGR0Q2R2UVVUWlBEN21rNzlRVEtRcGpObWp3dEtuNitZVERROUIvCkFHVnJucjdiVXBiU3ZlcWZUTzg0bXJldFFhRUhjUlJGdWxQN0RjMjJ0WEE4emNzVncxRlVzYmVXWWJQR3BHMzcKbzV6akw1aDl4TDhzYmhPOE9sTEdRZ0h5R1RhUG9rRUV6dTFrSVFlalRlUytNNGlIWVV2UTgxL3pWMk9pdFFkMAo3MlJCUFY1Yk9sZlpoQi9jVHlsS2dlYUJzd0lEQVFBQm80R2RNSUdhTUIwR0ExVWREZ1FXQkJTOHhmd0cvME9TCmxxY25BSWZJY0U1Z0pGSExEREFmQmdOVkhTTUVHREFXZ0JTOHhmd0cvME9TbHFjbkFJZkljRTVnSkZITEREQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NRWNHQTFVZEVRUkFNRDZDRTNkbFltaHZiMnN1WTNKdmJtcHZZaTV6ZG1PQwpJWGRsWW1odmIyc3VZM0p2Ym1wdllpNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJJY0V3S2d5d1RBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FnRUFqSHEwVTcrc3JIc3VMU1NteFpsMlgrTjgxcTBJSStrTEVIQlh2Qk0zdm0rbElHcHMKQjlNd3ZHMUViNGtZSWRjZVZDSm02bXR3aG1kTmJRN0c3cy9XS3RLMHFJOWt2RDIzU01sOW1KalVQN0tvZDdyOApEOFU1dlE0TVRaMWNidjNxZnFSMmgxcm0zZmVCVG5udGFrZzF0VEhXcS9UNkdTVmJKR0xDSm1EaTNISWU5WGpNCmZoZkRpMHRocG85b2NidG0xbTZHK0JRVmFDZDF3elR2aUhTVFRCVFV6SW1Xc2VKell3WldZd3dKa3ZBNVNOdFYKWGJyRThVUlhkRjBJRFpDYUY3TnUvclo4RTdvSXN6MkhPQzAvSDdhZlVuODNkUlRWZVo3a1J5b2lQaEM2dEM4dQpDSlNJQ0oyd0dzT1ZPdlRqNWRoZmpFYzZZR1h1U2xYb2NiK2lwNld4S2ZtSE5TVkxlUkhUUjB5UWQ1emRRb1dBCjRIZ0VZdVpZTTFLZVpzZ2YvaUZFbXpWMUJ2SWxUbGg5K2owTDBWejdyek5BZzJnUXlhR3YyNG5JaHhmYUVhWEUKeGd6aHdFOWpwTFBzalJCUDZHU3pQRDRJOFRFd2lPdGZJdVNFamVNS1Z2aFlEaFBkWjhERUIyd1pQL3E1clUyLwpvVUNsWlZYM05qKzdCcTRyNjVRU29CTEMzcUlwT2NMODFnY2pxVWVoNnNxeGxqZmdwRmd6ZHdMTEtrZm1rOVJ1CjBVeENLUlRZRWMrSzU3aWhvb0dMOGNWT3RrUkxWYUhVVDhxQldJR2hDenViRU4wa2hCdlFQaDAwaENjRFJBdWgKZkZHaFFmUy9xd242QnFxTDRmcWluZmFma0k5Um1OTkN1V0dDUFRtVW00a3hIdjNJQW1rL3BPNjFJSmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    failurePolicy: Fail
    name: mcronjob.kb.io
    rules:
      - apiGroups:
          - batch.tutorial.chanshik.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cronjobs
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      url: https://192.168.50.193:9443/validate-batch-tutorial-chanshik-dev-v1-cronjob
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhRENDQTFDZ0F3SUJBZ0lVRXMwbEFqWWZMUm45NnhpOVhyaHNadmlZcmNJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hqRWNNQm9HQTFVRUF3d1RkMlZpYUc5dmF5NWpjbTl1YW05aUxuTjJZekFlRncweU1UQTFNVEF3TlRVNQpNRFphRncweU1qQTFNVEF3TlRVNU1EWmFNQjR4SERBYUJnTlZCQU1NRTNkbFltaHZiMnN1WTNKdmJtcHZZaTV6CmRtTXdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFERE43ckFydXlQNmNuUVFYeW0KRk13dnRoYW1mbDIvSG5Tc2FDUmNhYTVOMWRETU9FcWRKc25MeVN4L1J0MWxPOVQxWmNjSkRZanRla1hmYWE1MgpvMDYyZE1HZGlJVHN5LzNpUmRDU0JVcXA1WnVVR3FGeE1lbkk1bDRSTjh0OFMwSnFsRlJUZlNSUHFyYUR5VWdaCnZoUHBYckJ1RXlpS1NEK1hQeDdTdHJheWNmM1NrMG9WVGhPZVlEWHYvV2JzdVpDOGhWMHR1OVp3OGhIamlsWGEKVHZwNVR6NDl6THlPQ09EM2I4OHBIa1FzbG80TkVZZkVGYnZFS2VWQkYyZzRJaHlLSmVoaTlySWR0MlpHcnlzQwpua3k0UitEVXVaZGk0N0JYN1pVdUE2azE2QnZUTjNVMmdlSFFJbTVDaFJtVjFxdGFPNVZ0NVNUTjRIbVF1alNrCkk2VUpnUktWQ2JmblJ2N3hha1QreHpQK3Bjb1h4ME94dWdPQ042LzVCY2k5UzBDVmVNM25EMVNHcG5rdHl0QnkKR1ZpZzM4RVRVUTNkdzJVaFd5QkFJdG9JT1p5VGRCdnNVTm9LT29sNjcwemJSMnRKRGJpdXZNZ20rTVhuV1YvbgpwQ1N1UWZFTDYxU1JLditvdkZiZklqUUt3ZGR0Q2R2UVVUWlBEN21rNzlRVEtRcGpObWp3dEtuNitZVERROUIvCkFHVnJucjdiVXBiU3ZlcWZUTzg0bXJldFFhRUhjUlJGdWxQN0RjMjJ0WEE4emNzVncxRlVzYmVXWWJQR3BHMzcKbzV6akw1aDl4TDhzYmhPOE9sTEdRZ0h5R1RhUG9rRUV6dTFrSVFlalRlUytNNGlIWVV2UTgxL3pWMk9pdFFkMAo3MlJCUFY1Yk9sZlpoQi9jVHlsS2dlYUJzd0lEQVFBQm80R2RNSUdhTUIwR0ExVWREZ1FXQkJTOHhmd0cvME9TCmxxY25BSWZJY0U1Z0pGSExEREFmQmdOVkhTTUVHREFXZ0JTOHhmd0cvME9TbHFjbkFJZkljRTVnSkZITEREQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NRWNHQTFVZEVRUkFNRDZDRTNkbFltaHZiMnN1WTNKdmJtcHZZaTV6ZG1PQwpJWGRsWW1odmIyc3VZM0p2Ym1wdllpNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJJY0V3S2d5d1RBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FnRUFqSHEwVTcrc3JIc3VMU1NteFpsMlgrTjgxcTBJSStrTEVIQlh2Qk0zdm0rbElHcHMKQjlNd3ZHMUViNGtZSWRjZVZDSm02bXR3aG1kTmJRN0c3cy9XS3RLMHFJOWt2RDIzU01sOW1KalVQN0tvZDdyOApEOFU1dlE0TVRaMWNidjNxZnFSMmgxcm0zZmVCVG5udGFrZzF0VEhXcS9UNkdTVmJKR0xDSm1EaTNISWU5WGpNCmZoZkRpMHRocG85b2NidG0xbTZHK0JRVmFDZDF3elR2aUhTVFRCVFV6SW1Xc2VKell3WldZd3dKa3ZBNVNOdFYKWGJyRThVUlhkRjBJRFpDYUY3TnUvclo4RTdvSXN6MkhPQzAvSDdhZlVuODNkUlRWZVo3a1J5b2lQaEM2dEM4dQpDSlNJQ0oyd0dzT1ZPdlRqNWRoZmpFYzZZR1h1U2xYb2NiK2lwNld4S2ZtSE5TVkxlUkhUUjB5UWQ1emRRb1dBCjRIZ0VZdVpZTTFLZVpzZ2YvaUZFbXpWMUJ2SWxUbGg5K2owTDBWejdyek5BZzJnUXlhR3YyNG5JaHhmYUVhWEUKeGd6aHdFOWpwTFBzalJCUDZHU3pQRDRJOFRFd2lPdGZJdVNFamVNS1Z2aFlEaFBkWjhERUIyd1pQL3E1clUyLwpvVUNsWlZYM05qKzdCcTRyNjVRU29CTEMzcUlwT2NMODFnY2pxVWVoNnNxeGxqZmdwRmd6ZHdMTEtrZm1rOVJ1CjBVeENLUlRZRWMrSzU3aWhvb0dMOGNWT3RrUkxWYUhVVDhxQldJR2hDenViRU4wa2hCdlFQaDAwaENjRFJBdWgKZkZHaFFmUy9xd242QnFxTDRmcWluZmFma0k5Um1OTkN1V0dDUFRtVW00a3hIdjNJQW1rL3BPNjFJSmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    failurePolicy: Fail
    name: vcronjob.kb.io
    rules:
      - apiGroups:
          - batch.tutorial.chanshik.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - cronjobs
    sideEffects: None
